### ISSUE TITLE
crate doesn't exist?

### ISSUE THREAD

**Issue by JimLynchCodes** [a11ywatch/rust-to-npm#8]
I run ` npm i rust-to-npm-cli -g` but it doesn't seem to work...

Instead it fails with this error:
```
Installing and compiling rust-to-npm-cli 0.4.10  ...

Error: Command failed: cargo install rust-to-npm-cli --vers 0.4.10 
    Updating crates.io index
error: could not find `rust-to-npm-cli` in registry `crates-io` with version `=0.4.10`

    at ChildProcess.exithandler (child_process.js:383:12)
    at ChildProcess.emit (events.js:400:28)
    at maybeClose (internal/child_process.js:1088:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:296:5) {
  killed: false,
  code: 101,
  signal: null,
  cmd: 'cargo install rust-to-npm-cli --vers 0.4.10 '
}
```

**Comment by JimLynchCodes** [comment]
it seems to be looking for a crate calle
![Screen Shot 2023-05-17 at 1 25 37 AM](https://github.com/a11ywatch/rust-to-npm/assets/5354163/af80eab3-824e-4012-8bf3-6b55bfbb4e72)
d "rust-to-npm-cli" which doens't exist at all on crates.io

**Comment by j-mendez** [comment]
@JimLynchCodes thank you, published now https://crates.io/crates/rust-to-npm-cli. We moved the crate from https://crates.io/crates/rust-to-npm/0.4.9 which prior was the CLI and split the rust crate with the CLI.
